// List of interesting prompts to randomly sample.
export const samplePrompts = [
    "lo-fi beat for the holidays",
    "techno DJ and a country singer",
    "classical italian tenor operatic pop",
    "arabic (vocals:1.5)",
    "typing",
    "chainsaw funk",
    "dance pop edm electropop indietronica metropopolis pop uk pop",
    "kygo tropical dance marvin gaye",
    "west coast rap vocals 808",
    "church bells",
    "funk bassline with a jazzy saxophone solo",
    "piano funk",
    "a jazz pianist playing a concerto",
    "rock and roll electric guitar solo",
    "acoustic folk fiddle jam",
    "jamaican rap",
    "church organ with a harpsichord",
    "mambo but from kenya",
    "classical flute",
    "swing jazz trumpet",
    "tropical deep sea",
    "laughing",
    "lo-fi beat with a violin",
];
