// List of interesting prompts to randomly sample.
export const samplePrompts = [
  "a folksy blues song from the mississippi delta around 1910",
  "acoustic folk violin jam",
  "ancient chinese hymn",
  "anger rap",
  "arabic gospel vocals",
  "bongos on a havana street",
  "bossa nova with distorted guitar",
  "bubblegum eurodance",
  "church bells",
  "classical italian tenor operatic pop",
  "copacabana beach",
  "deep, smooth synthwave with a dream-like atmosphere",
  "emotional disco",
  "funk bassline with a jazzy saxophone",
  "ibiza at 3am",
  "jamaican dancehall vocals",
  "jazzy clarinet with maracas",
  "jazzy rapping from paris",
  "k-pop boy group",
  "latent space vaporwave",
  "lo-fi beat for the holidays",
  "mambo but from Kenya",
  "piano concerto in A minor",
  "post-teen pop talent show winner",
  "psychedelic nepalese trance",
  "rock and roll electric guitar solo",
  "scott joplin style ragtime piano",
  "smooth tropical dance jazz",
  "swing jazz trumpet",
  "techno DJ and a country fiddle",
  "typing",
];

export const rollTheDicePrompts = [
  "(caribbean:1.5) (jazz:0.3)",
  "alarm clock",
  "bird calls",
  "baroque new wave pop",
  "Berlin and Paris electronic fused together with acoustic tunes",
  "breathing",
  "brazilian Forró dance",
  "british soul dance",
  "chainsaw funk",
  "church organ with a harpsichord",
  "classic rock mellow gold progressive",
  "classical flute",
  "cowbell ballad",
  "funky human music",
  "hip hop vocals piano cowbell",
  "interdimensional cable",
  "jamaican ska rap",
  "laughing",
  "lucky disco punk",
  "new orleans blues",
  "piano funk",
  "pop r&b urban contemporary",
  "reggae fusion",
  "Shepard tone",
  "smelly clown",
  "square dancing in wyoming",
  "tropical deep sea",
  "tropical electro house moombahton",
  "tropical german dance house",
  "uk permanent wave pop",
  "water drops",
  "west coast rap vocals",
];

export const initialSeedImageMap = {
  "og_beat": [3, 738973, 674, 745234, 808, 231, 3324, 323984, 123, 51209, 123, 51209, 6754, 8730],
  "agile": [808, 231, 3324, 323984],
  "marim": [123, 51209, 6754, 8730],
  "motorway": [8730, 323984, 745234],
  "vibes": [4205, 94, 78530]
}

export const initialSeeds = [
  "og_beat",
  // "agile",
  // "marim",
  // "motorway",
  // "vibes"
]
